In [1]:
import pandas as pd
import numpy as np
import datetime

# Read in file and set it up

In [2]:
# import the csv file - got a dtype error, used low_memory = False since this notebook is just for cleaning
# and a different csv will be used
smile_on = pd.read_csv('../data/Smileon.2021.10.17.csv', parse_dates = True, header=None, low_memory = False)

In [3]:
smile_on.head()

,0,1,2,3,4,5,6,7,8,9,...,174,175,176,177,178,179,180,181,182,183
0,FamilyandChildrensService - CallReports export...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CallReportNum,ReportVersion,LinkedToCallReportNum,CallDateAndTimeStart,CallDateAndTimeEnd,CallLength,CallerNum,PhoneWorkerNum,WasRealCall,WasHangup,...,SMILE ON 60+ Screening - Treatment Urgency,SMILE ON 60+ Screening - Untreated Decay,SMILE ON 60+ Site Information - Enroller ID,SMILE ON 60+ Site Information - Enroller Location,SMILE ON 60+ Treatment Plan - Action: Upload A...,SMILE ON 60+ Treatment Plan - Is the treatment...,SMILE ON 60+ Treatment Plan - Was a treatment ...,SMILE ON 60+ Treatment Plan - Was the enrollee...,SMILE ON 60+ Verification of Eligibility - Tra...,SMILE ON 60+ Verification of Eligibility - Ver...
3,93115324,SMILE ON 60+ Registration,NaN,9/30/2021 16:56,9/30/2021 16:57,1,3638169,123747,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,93115188,SMILE ON 60+ Registration,NaN,9/30/2021 16:53,9/30/2021 16:53,0,4431194,123747,NaN,NaN,...,NaN,NaN,NaN,Referral Follow-Up,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
smile_on.shape

(57863, 184)

In [5]:
#got this from stack exhange - take a row and make it the header
new_header = smile_on.iloc[2] #grab the first row for the header
smile_on = smile_on[3:] #take the data less the header row
smile_on.columns = new_header #set the header row as the df header
smile_on.head()

2,CallReportNum,ReportVersion,LinkedToCallReportNum,CallDateAndTimeStart,CallDateAndTimeEnd,CallLength,CallerNum,PhoneWorkerNum,WasRealCall,WasHangup,...,SMILE ON 60+ Screening - Treatment Urgency,SMILE ON 60+ Screening - Untreated Decay,SMILE ON 60+ Site Information - Enroller ID,SMILE ON 60+ Site Information - Enroller Location,SMILE ON 60+ Treatment Plan - Action: Upload After Picture on Finish Tab,SMILE ON 60+ Treatment Plan - Is the treatment plan completed?,SMILE ON 60+ Treatment Plan - Was a treatment plan developed?,"SMILE ON 60+ Treatment Plan - Was the enrollee able to be restored to function (can chew) and ""social six"" esthetics (top front six teeth are present and disease free)",SMILE ON 60+ Verification of Eligibility - Transportation Arranged,SMILE ON 60+ Verification of Eligibility - Verification of Eligibility
3,93115324,SMILE ON 60+ Registration,NaN,9/30/2021 16:56,9/30/2021 16:57,1,3638169,123747,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,93115188,SMILE ON 60+ Registration,NaN,9/30/2021 16:53,9/30/2021 16:53,0,4431194,123747,NaN,NaN,...,NaN,NaN,NaN,Referral Follow-Up,NaN,NaN,NaN,NaN,NaN,NaN
5,93115081,SMILE ON 60+ Clinical,NaN,9/30/2021 16:50,9/30/2021 16:51,1,2941341,161979,NaN,NaN,...,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,NaN,No,Yes,No,NaN,NaN
6,93115032,SMILE ON 60+ Clinical,NaN,9/30/2021 16:48,9/30/2021 16:49,1,3823933,161979,NaN,NaN,...,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,NaN,No,Yes,No,NaN,NaN
7,93114968,SMILE ON 60+ Clinical,NaN,9/30/2021 16:46,9/30/2021 16:48,2,3348256,161979,NaN,NaN,...,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,NaN,No,Yes,No,NaN,NaN

In [6]:
smile_on.shape

(57860, 184)

In [7]:
smile_on.reset_index(inplace=True, drop=True)

In [8]:
smile_on.head()

2,CallReportNum,ReportVersion,LinkedToCallReportNum,CallDateAndTimeStart,CallDateAndTimeEnd,CallLength,CallerNum,PhoneWorkerNum,WasRealCall,WasHangup,...,SMILE ON 60+ Screening - Treatment Urgency,SMILE ON 60+ Screening - Untreated Decay,SMILE ON 60+ Site Information - Enroller ID,SMILE ON 60+ Site Information - Enroller Location,SMILE ON 60+ Treatment Plan - Action: Upload After Picture on Finish Tab,SMILE ON 60+ Treatment Plan - Is the treatment plan completed?,SMILE ON 60+ Treatment Plan - Was a treatment plan developed?,"SMILE ON 60+ Treatment Plan - Was the enrollee able to be restored to function (can chew) and ""social six"" esthetics (top front six teeth are present and disease free)",SMILE ON 60+ Verification of Eligibility - Transportation Arranged,SMILE ON 60+ Verification of Eligibility - Verification of Eligibility
0,93115324,SMILE ON 60+ Registration,NaN,9/30/2021 16:56,9/30/2021 16:57,1,3638169,123747,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93115188,SMILE ON 60+ Registration,NaN,9/30/2021 16:53,9/30/2021 16:53,0,4431194,123747,NaN,NaN,...,NaN,NaN,NaN,Referral Follow-Up,NaN,NaN,NaN,NaN,NaN,NaN
2,93115081,SMILE ON 60+ Clinical,NaN,9/30/2021 16:50,9/30/2021 16:51,1,2941341,161979,NaN,NaN,...,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,NaN,No,Yes,No,NaN,NaN
3,93115032,SMILE ON 60+ Clinical,NaN,9/30/2021 16:48,9/30/2021 16:49,1,3823933,161979,NaN,NaN,...,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,NaN,No,Yes,No,NaN,NaN
4,93114968,SMILE ON 60+ Clinical,NaN,9/30/2021 16:46,9/30/2021 16:48,2,3348256,161979,NaN,NaN,...,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,NaN,No,Yes,No,NaN,NaN

# Explore to begin cleaning

In [9]:
#explore to see if columns need to be dropped
drop = smile_on['ThirdPartyStateProvince'].unique()
drop

array([nan, 'TN'], dtype=object)

In [10]:
#explore to see if columns need to be dropped
drop = smile_on['FeedbackStatus'].unique()
drop

array(['Not yet', 'Seen', 'Not needed', 'To be read'], dtype=object)

In [11]:
#explore to see if columns need to be dropped
drop = smile_on['FeedbackFromPhoneWorkerNum'].unique()
drop

array([nan, '117268', '82339', '116749', '118292', '-1', '82341',
       '117266', '60132'], dtype=object)

In [12]:
#explore to see if columns need to be dropped
drop = smile_on['FeedbackStatus'].unique()
drop

array(['Not yet', 'Seen', 'Not needed', 'To be read'], dtype=object)

In [13]:
#explore to see if columns need to be dropped
drop = smile_on['SMILE ON 60+ Case Management Information - What barriers have kept you from finding a consistent dental home? (Select all that apply)'].unique()
drop

array(['No insurance', 'Dental cost; No insurance',
       'Dental cost; No insurance; Fear',
       'Transportation; Dental cost; No insurance', 'Dental cost', nan,
       'Dental cost; No insurance; Personal isolation',
       'Dental cost; No insurance; Physical mobility and health',
       'No insurance; Physical mobility and health', 'No insurance; Fear',
       'Transportation; Dental cost; No insurance; Personal isolation; Fear; Physical mobility and health',
       'Transportation; Dental cost',
       'Transportation; Dental cost; No insurance; Physical mobility and health',
       'Fear', 'Dental cost; Fear',
       'No insurance; Fear; Physical mobility and health',
       'Transportation; Dental cost; No insurance; Fear',
       'Transportation; Dental cost; Fear',
       'Transportation; No insurance',
       'Dental cost; No insurance; Fear; Physical mobility and health',
       'Dental cost; Physical mobility and health',
       'Dental cost; Fear; Physical mobility and health',
       'Transportation; Dental cost; No insurance; Fear; Physical mobility and health',
       'Transportation',
       'Transportation; Dental cost; Physical mobility and health',
       'Transportation; Dental cost; No insurance; Personal isolation',
       'Personal isolation',
       'Dental cost; No insurance; Personal isolation; Fear; Physical mobility and health',
       'Physical mobility and health', 'Personal isolation; Fear',
       'Dental cost; No insurance; Personal isolation; Fear',
       'No insurance; Personal isolation',
       'Transportation; Dental cost; No insurance; Personal isolation; Fear',
       'Transportation; Dental cost; Personal isolation',
       'Dental cost; Personal isolation; Fear',
       'Transportation; Personal isolation',
       'Dental cost; No insurance; Personal isolation; Physical mobility and health',
       'Transportation; No insurance; Physical mobility and health',
       'Dental cost; Personal isolation',
       'Transportation; Dental cost; Personal isolation; Physical mobility and health',
       'Transportation; Physical mobility and health',
       'Transportation; No insurance; Fear; Physical mobility and health',
       'Transportation; Dental cost; Fear; Physical mobility and health',
       'Transportation; Dental cost; No insurance; Personal isolation; Physical mobility and health',
       'Fear; Physical mobility and health',
       'Personal isolation; Physical mobility and health',
       'Transportation; No insurance; Fear',
       'Dental cost; Personal isolation; Physical mobility and health',
       'Transportation; No insurance; Personal isolation',
       'Transportation; Fear', 'Transportation; Personal isolation; Fear',
       'Transportation; Fear; Physical mobility and health',
       'Transportation; Personal isolation; Physical mobility and health'],
      dtype=object)

In [14]:
# drop all columns that only have null values
smile_on = smile_on.dropna(axis=1,how='all')
#drop columns with information that is not useful
smile_on = smile_on.drop('OrgNum', axis=1)
smile_on = smile_on.drop('SMILE ON 60+ Treatment Plan - Action: Upload After Picture on Finish Tab', axis=1)
smile_on = smile_on.drop('SMILE ON 60+ Clinic Information - Action: Upload Before Picture on Finish Tab', axis=1)
smile_on = smile_on.drop('CountryName', axis=1)
smile_on = smile_on.drop('PhoneType', axis=1)
smile_on = smile_on.drop('ThirdPartyStateProvince', axis=1)
smile_on = smile_on.drop('FeedbackFromPhoneWorkerNum', axis=1)
smile_on = smile_on.drop('FeedbackFromPhoneWorkerName', axis=1)
smile_on = smile_on.drop('Narrative', axis=1)
smile_on = smile_on.drop('PhoneWorkerNum', axis=1)
smile_on = smile_on.drop('SMILE ON 60+ Notes (Optional) - Notes', axis=1)
smile_on = smile_on.drop('Feedback', axis=1)
smile_on = smile_on.drop('FeedbackStatus', axis=1)
smile_on = smile_on.drop('Reviewed', axis=1)
smile_on = smile_on.drop('SMILE ON 60+ Oral Care Encounter - Lab Assist narrative', axis=1)
smile_on.shape

(57860, 115)

In [15]:
# regex to change strings in column names
# can also remove plus with ('SMILE ON 60\\+')
smile_on.columns = smile_on.columns.str.replace(r'SMILE ON 60\+ ', '')
smile_on.columns = smile_on.columns.str.replace('Oral Care Encounter - ', 'oec_')
smile_on.columns = smile_on.columns.str.replace(' - Quantity', '')
smile_on.columns = smile_on.columns.str.replace('Demographic Information - ', 'di_')
smile_on.columns = smile_on.columns.str.replace('Base-line Oral and Conditions Questions - ', 'bocq_')
smile_on.columns = smile_on.columns.str.replace('Screening - ', 'scrn_')
smile_on.columns = smile_on.columns.str.replace('Treatment Plan - ', 'tp_')
smile_on.columns = smile_on.columns.str.replace('Presumptive Eligibility - ', 'pe_')
smile_on.columns = smile_on.columns.str.replace('Case Management Information - ', 'cmi_')
smile_on.columns = smile_on.columns.str.replace('Clinic Information - ', 'ci_')
smile_on.columns = smile_on.columns.str.replace('Verification of Eligibility - ', 've_')
smile_on.columns = smile_on.columns.str.replace('Site Information - ', 'si_')

<ipython-input-15-1f411c6eba5a>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  smile_on.columns = smile_on.columns.str.replace(r'SMILE ON 60\+ ', '')

In [16]:
print(smile_on.columns.tolist())

['CallReportNum', 'ReportVersion', 'LinkedToCallReportNum', 'CallDateAndTimeStart', 'CallDateAndTimeEnd', 'CallLength', 'CallerNum', 'CityName', 'CountyName', 'StateProvince', 'PostalCode', 'EnteredByWorkerNum', 'EnteredOn', 'ReferralsMade', 'di_# of People in Household', 'Birth Year', 'di_Other Language', 'oec_1351', 'oec_1354', 'oec_2140', 'oec_2150', 'oec_2160', 'oec_2161', 'oec_230', 'oec_2330', 'oec_2331', 'oec_2332', 'oec_2335', 'oec_2390', 'oec_2391', 'oec_2392', 'oec_2393', 'oec_2394', 'oec_2915', 'oec_2920', 'oec_2933', 'oec_2940', 'oec_2950', 'oec_2954', 'oec_2980', 'oec_3220', 'oec_4341', 'oec_4342', 'oec_6930', 'oec_6980', 'oec_7111', 'oec_7140', 'oec_7210', 'oec_7220', 'oec_7230', 'oec_7240', 'oec_7241', 'oec_7250', 'oec_7261', 'oec_7286', 'oec_7310', 'oec_7311', 'oec_7320', 'oec_7321', 'oec_7410', 'oec_7411', 'oec_7471', 'oec_7510', 'oec_7971', 'oec_7972', 'oec_9110', 'oec_9951', 'scrn_Last Screening Date', 've_Verification Date', 'bocq_Are you limited in what you can eat?', 'bocq_Dental Clinic', 'bocq_Did the client commit to referral?', 'bocq_Did you help in these other areas?', 'bocq_Do you need help in these other areas?', 'bocq_Have you ever felt that the appearance of your mouth and teeth affected your quality of life?', 'bocq_How would you describe the condition of your mouth and teeth?', 'bocq_What is the next step for client encounter?', 'bocq_What is the next step for clients encounter?', 'cmi_Dental Clinic', 'cmi_Transportation Barriers', 'cmi_What barriers have kept you from finding a consistent dental home? (Select all that apply)', 'cmi_What is the outcome for the client?', 'ci_Is patient of record date if yes last seen?', 'ci_Was initial appointment made?', 'ci_Was initial transportation assistance or referral provided?', 'di_Gender', 'di_Household Income Level', 'di_How did you first hear about the program?', 'di_Preferred Language/Language Needed', 'di_Race/Ethnicity', 'di_What other assistance programs are you on?', 'di_When is the last time you visited your dentist?', 'oec_What care was provided to the enrollee? (Select all that apply)', 'pe_Dental Insurance?', 'pe_Do they pre-qualify for SMILE ON 60+?', 'pe_What is the next step for clients encounter? ', 'pe_What is the next step for clients encounter?', 'scrn_# of Lower Natural Teeth', 'scrn_# of Upper Natural Teeth', 'scrn_Do you have removable dentures?', 'scrn_Do you usually wear your denture(s) when you eat?', 'scrn_Experienced any problems related to mouth/teeth during past 12 months?', 'scrn_How often do you brush your teeth?', 'scrn_Need for Periodontal Care', 'scrn_Root Fragments', 'scrn_Suspicious Soft Tissue Lesions', 'scrn_Treatment Urgency', 'scrn_Untreated Decay', 'si_Enroller ID', 'si_Enroller Location', 'tp_Is the treatment plan completed?', 'tp_Was a treatment plan developed?', 'tp_Was the enrollee able to be restored to function (can chew) and "social six" esthetics (top front six teeth are present and disease free)', 've_Transportation Arranged', 've_Verification of Eligibility']

In [17]:
#change column names
smile_on = smile_on.rename(columns={
'CallReportNum': 'report_num',
'ReportVersion': 'reg_or_appt',
'LinkedToCallReportNum': 'related_reports',
'CallDateAndTimeStart': 'call_start',
'CallDateAndTimeEnd': 'call_end',
'CallLength': 'call_length',
'CallerNum': 'patient_id',
#'PhoneWorkerNum': 'worker_id',
'CityName': 'city',
'CountyName': 'county',
'StateProvince': 'state',
'PostalCode': 'zip_code',
#'Narrative': 'narrative',
#'Feedback': 'feedback',
'EnteredOn': 'date_entered',
#'Reviewed': 'reviewed',
#'FeedbackStatus': 'feedback_status',
'ReferralsMade': 'referrals_made',
'Birth Year': 'birth_year',
'di_# of People in Household': 'di_household_size',
#'Notes (Optional) - Notes': 'notes_optional'
#'oec_Lab Assist narrative': 'oec_lab_narrative',
'scrn_Last Screening Date': 'scrn_date_of_last',
've_Verification Date': 've_verified_date',
'bocq_Are you limited in what you can eat?': 'bocq_eat_limited',
'bocq_Dental Clinic': 'bocq_dental_clinic',
'bocq_Did the client commit to referral?': 'bocq_client_commit',
'bocq_Did you help in these other areas?': 'bocq_help_other',
'bocq_Do you need help in these other areas?': 'bocq_need_help',
'bocq_Have you ever felt that the appearance of your mouth and teeth affected your quality of life?': 'bocq_appearance',
'bocq_How would you describe the condition of your mouth and teeth?': 'bocq_condition',
'tp_Is the treatment plan completed?': 'tp_completed',
'tp_Was a treatment plan developed?': 'tp_developed',
'tp_Was the enrollee able to be restored to function (can chew) and "social six" esthetics (top front six teeth are present and disease free)': 'tp_yay',
'bocq_What is the next step for client encounter?': 'bocq_next_step1',
'bocq_What is the next step for clients encounter?': 'bocq_next_step2',
'di_Gender': 'di_gender',
'di_Household Income Level': 'di_hh_income',
'di_How did you first hear about the program?': 'di_referred_by',
'di_Preferred Language/Language Needed': 'di_language1',
'di_Other Language': 'di_other_language',
'di_Race/Ethnicity': 'di_race_eth',
'di_What other assistance programs are you on?':'di_other_programs',
'di_When is the last time you visited your dentist?': 'di_last_dentist_visit',
'oec_What care was provided to the enrollee? (Select all that apply)': 'oec_care_provided',
'scrn_# of Lower Natural Teeth': 'scrn_lower_teeth',
'scrn_# of Upper Natural Teeth': 'scrn_upper_teeth',
'scrn_Do you have removable dentures?': 'scrn_has_dentures',
'scrn_Do you usually wear your denture(s) when you eat?': 'scrn_eats_w_dentures',
'scrn_Experienced any problems related to mouth/teeth during past 12 months?': 'scrn_problems_12m',
'scrn_How often do you brush your teeth?': 'scrn_tooth_brushing',
'scrn_Need for Periodontal Care': 'scrn_periodontal',
'scrn_Root Fragments': 'scrn_root_fragments',
'scrn_Suspicious Soft Tissue Lesions': 'scrn_lesions',
'scrn_Treatment Urgency': 'scrn_urgency',
'scrn_Untreated Decay': 'scrn_decay',
'si_Enroller ID': 'si_enroller_id',
'si_Enroller Location': 'si_enroller_location',
've_Transportation Arranged': 've_transport',
've_Verification of Eligibility': 've_eligibility_verified',
'cmi_Transportation Barriers': 'cmi_transport_barriers',
'pe_What is the next step for clients encounter? ': 'pe_next_step1',
'pe_What is the next step for clients encounter?': 'pe_next_step2',
'pe_Dental Insurance?' : 'pe_insurance',
'pe_Do they pre-qualify for SMILE ON 60+?' : 'pe_prequalify',
'cmi_Dental Clinic' : 'cmi_clinic',
'cmi_What barriers have kept you from finding a consistent dental home? (Select all that apply)': 'cmi_barriers_to_care'})

In [18]:
smile_on.head()

2,report_num,reg_or_appt,related_reports,call_start,call_end,call_length,patient_id,city,county,state,...,scrn_lesions,scrn_urgency,scrn_decay,si_enroller_id,si_enroller_location,tp_completed,tp_developed,tp_yay,ve_transport,ve_eligibility_verified
0,93115324,SMILE ON 60+ Registration,NaN,9/30/2021 16:56,9/30/2021 16:57,1,3638169,Smyrna,Rutherford,TN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93115188,SMILE ON 60+ Registration,NaN,9/30/2021 16:53,9/30/2021 16:53,0,4431194,Nashville,Davidson,TN,...,NaN,NaN,NaN,NaN,Referral Follow-Up,NaN,NaN,NaN,NaN,NaN
2,93115081,SMILE ON 60+ Clinical,NaN,9/30/2021 16:50,9/30/2021 16:51,1,2941341,Memphis,Shelby,TN,...,NaN,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,No,Yes,No,NaN,NaN
3,93115032,SMILE ON 60+ Clinical,NaN,9/30/2021 16:48,9/30/2021 16:49,1,3823933,Memphis,Shelby,TN,...,NaN,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,No,Yes,No,NaN,NaN
4,93114968,SMILE ON 60+ Clinical,NaN,9/30/2021 16:46,9/30/2021 16:48,2,3348256,Memphis,Shelby,TN,...,NaN,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,No,Yes,No,NaN,NaN

Comparing care provided column listed procedures to columns of that procedure

In [19]:
smile_on.loc[:,['oec_care_provided', 'oec_2391', 'oec_2392']]

2                                      oec_care_provided oec_2391 oec_2392
0                                                    NaN      NaN      NaN
1                                                    NaN      NaN      NaN
2      274 - Bitewings - four films - 5; 1110 - Proph...      NaN      NaN
3      2391 - Posterior one surface resin  - 15; 2392...        2        1
4      No Code - Denture step Mandibular: may be used...      NaN      NaN
...                                                  ...      ...      ...
57855  5222 - Partial denture - resin base - immediat...      NaN      NaN
57856                                                NaN      NaN      NaN
57857                                                NaN      NaN      NaN
57858                                                NaN      NaN      NaN
57859                                                NaN      NaN      NaN

[57860 rows x 3 columns]

# Base-Line Oral and Condition Columns - merging two columns together

In [20]:
#cell to compare contents of two different columns
smile_on.loc[:,['bocq_next_step1', 'bocq_next_step2']].head(10)
#filter where they're both not null and - for each column
#next step - 1 not null
#next stop - 2 not null

2            bocq_next_step1            bocq_next_step2
0                        NaN  Referred to dental clinic
1                        NaN  Referred to dental clinic
2  Referred to dental clinic                        NaN
3                        NaN                        NaN
4                        NaN                        NaN
5                        NaN  Referred to dental clinic
6                        NaN  Referred to dental clinic
7                        NaN  Referred to dental clinic
8                        NaN                        NaN
9                        NaN                        NaN

In [21]:
#are any rows that are not null in bocq1 also not null in bocq2?
compare_next_step = (smile_on['bocq_next_step1'].notnull() == smile_on['bocq_next_step2'].notnull()).all()
compare_next_step

False

In [22]:
# where rows are both null
smile_on.loc[(smile_on['bocq_next_step1'].isnull()) & (smile_on['bocq_next_step2'].isnull())]

2,report_num,reg_or_appt,related_reports,call_start,call_end,call_length,patient_id,city,county,state,...,scrn_lesions,scrn_urgency,scrn_decay,si_enroller_id,si_enroller_location,tp_completed,tp_developed,tp_yay,ve_transport,ve_eligibility_verified
3,93115032,SMILE ON 60+ Clinical,NaN,9/30/2021 16:48,9/30/2021 16:49,1,3823933,Memphis,Shelby,TN,...,NaN,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,No,Yes,No,NaN,NaN
4,93114968,SMILE ON 60+ Clinical,NaN,9/30/2021 16:46,9/30/2021 16:48,2,3348256,Memphis,Shelby,TN,...,NaN,NaN,NaN,Christ Community Health Services- Broad Avenue,Provider Site,No,Yes,No,NaN,NaN
8,93114520,SMILE ON 60+ Clinical,NaN,9/30/2021 16:35,9/30/2021 16:37,2,4492947,Millington,Shelby,TN,...,NaN,NaN,NaN,Christ Community Health Services- Raleigh,Provider Site,No,Yes,No,NaN,Yes
9,93154018,SMILE ON 60+ Clinical,NaN,9/30/2021 16:09,9/30/2021 16:12,3,2887352,Memphis,Shelby,TN,...,No,No obvious problem,No,Christ Community Health Services- Broad Avenue,Provider Site,Yes,Yes,Yes,NaN,NaN
10,93292560,SMILE ON 60+ Clinical,NaN,9/30/2021 15:35,9/30/2021 15:36,1,2686768,White House,Robertson,TN,...,NaN,NaN,NaN,Neighborhood Health - Cleveland Park/ Nashville,Provider Site,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57854,55104302,SMILE ON 60+ Registration,NaN,8/1/2018 8:18,8/1/2018 9:43,85,2384744,Nashville,Davidson,TN,...,NaN,NaN,NaN,Interfaith Dental Clinic - Nashville,Provider Site,NaN,NaN,NaN,NaN,NaN
57855,55627514,SMILE ON 60+ Clinical,NaN,8/1/2018 8:00,8/1/2018 8:08,8,2385621,Lascassas,Rutherford,TN,...,NaN,NaN,NaN,Interfaith Dental Clinic - Murfreesboro,NaN,NaN,NaN,NaN,NaN,NaN
57856,67251452,SMILE ON 60+ Clinical,NaN,5/31/2018 8:27,5/31/2018 8:29,2,2631417,Kingsport,Sullivan,TN,...,NaN,NaN,NaN,Friends in Need Health Center - Kingsport,Provider Site,No,No,Yes,NaN,NaN
57857,53192452,SMILE ON 60+ Registration,NaN,5/23/2018 14:11,5/23/2018 14:11,0,-1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57859,67251405,SMILE ON 60+ Clinical,NaN,5/10/2018 8:25,5/10/2018 8:26,1,2631417,Kingsport,Sullivan,TN,...,NaN,NaN,NaN,Friends in Need Health Center - Kingsport,Provider Site,No,Yes,Yes,NaN,NaN

In [23]:
#cell to explore contents of various cells
bocq1 = smile_on['bocq_next_step1'].unique()
bocq1

array([nan, 'Referred to dental clinic', 'Care Coordinator',
       'Not interested in SMILE ON', 'Information Only'], dtype=object)

In [24]:
#cell to explore contents of various cells
bocq2 = smile_on['bocq_next_step2'].unique()
bocq2
#value count on services/wisdom tooth

array(['Referred to dental clinic', nan, 'Information Only',
       'Care Coordinator', 'Not interested in SMILE ON',
       'Services not available within SMILE ON', 'Wisdom Tooth Workshop'],
      dtype=object)

In [25]:
#checking value counts on question 2
smile_on["bocq_next_step2"].value_counts()

Referred to dental clinic                 12353
Care Coordinator                           1190
Information Only                            360
Not interested in SMILE ON                  150
Services not available within SMILE ON       13
Wisdom Tooth Workshop                         5
Name: bocq_next_step2, dtype: int64

In [26]:
#slice based on 2 unique values
bocq3=smile_on.loc[(smile_on["bocq_next_step2"] == "Wisdom Tooth Workshop")]
bocq3

2,report_num,reg_or_appt,related_reports,call_start,call_end,call_length,patient_id,city,county,state,...,scrn_lesions,scrn_urgency,scrn_decay,si_enroller_id,si_enroller_location,tp_completed,tp_developed,tp_yay,ve_transport,ve_eligibility_verified
29153,71334697,SMILE ON 60+ Registration,NaN,2/27/2020 16:53,2/27/2020 16:55,2,3219300,La Vergne,Rutherford,TN,...,NaN,NaN,NaN,NaN,Tooth Wisdom,NaN,NaN,NaN,NaN,NaN
43222,65222474,SMILE ON 60+ Registration,NaN,8/6/2019 15:27,8/6/2019 15:35,8,2832200,Clarksville,Montgomery,TN,...,NaN,NaN,NaN,Matthew Walker - Clarksville,Provider Site,NaN,NaN,NaN,NaN,NaN
49261,61894436,SMILE ON 60+ Registration,NaN,4/5/2019 10:10,4/5/2019 10:32,22,2754521,Sevierville,Sevier,TN,...,NaN,NaN,NaN,NaN,Health Assist Office,NaN,NaN,NaN,NaN,NaN
54266,58308976,SMILE ON 60+ Registration,NaN,11/28/2018 14:11,11/28/2018 14:28,17,2518608,Brentwood,Williamson,TN,...,NaN,NaN,NaN,NaN,Tooth Wisdom,NaN,NaN,NaN,NaN,NaN
54375,58249716,SMILE ON 60+ Registration,NaN,11/26/2018 15:58,11/26/2018 16:01,3,2515680,Eagleville,Rutherford,TN,...,NaN,NaN,NaN,NaN,Tooth Wisdom,NaN,NaN,NaN,NaN,NaN

In [27]:
bocq3.loc[:,['bocq_next_step1', 'bocq_next_step2']]

2     bocq_next_step1        bocq_next_step2
29153             NaN  Wisdom Tooth Workshop
43222             NaN  Wisdom Tooth Workshop
49261             NaN  Wisdom Tooth Workshop
54266             NaN  Wisdom Tooth Workshop
54375             NaN  Wisdom Tooth Workshop

In [28]:
#slice based on 2 unique values
bocq4=smile_on.loc[(smile_on["bocq_next_step2"] == "Services not available within SMILE ON")]
bocq4.loc[:,['bocq_next_step1', 'bocq_next_step2']]

2     bocq_next_step1                         bocq_next_step2
27524             NaN  Services not available within SMILE ON
36201             NaN  Services not available within SMILE ON
36999             NaN  Services not available within SMILE ON
39268             NaN  Services not available within SMILE ON
41926             NaN  Services not available within SMILE ON
44068             NaN  Services not available within SMILE ON
45063             NaN  Services not available within SMILE ON
48429             NaN  Services not available within SMILE ON
48431             NaN  Services not available within SMILE ON
51049             NaN  Services not available within SMILE ON
55655             NaN  Services not available within SMILE ON
57297             NaN  Services not available within SMILE ON
57352             NaN  Services not available within SMILE ON

In [29]:
smile_on['bocq_next_step'] = smile_on['bocq_next_step1'].fillna(smile_on['bocq_next_step2'])
smile_on = smile_on.drop('bocq_next_step1', axis=1)
smile_on = smile_on.drop('bocq_next_step2', axis=1)
smile_on.shape

(57860, 114)

In [30]:
#drop people who did not want care
smile_on = smile_on.drop(smile_on[smile_on.bocq_next_step.isin(
["Information Only", "Not Interested in SMILE ON", "Services not available within SMILE ON"])].index)
smile_on.shape

(57486, 114)

# Demographic Information - Language merging two columns together

In [31]:
#cell to explore contents of various cells
lang1 = smile_on['di_language1'].unique()
lang1

array(['English', nan, 'Other', 'Spanish', 'Arabic'], dtype=object)

In [32]:
smile_on["di_language1"].value_counts()

English    13691
Spanish     2126
Other        730
Arabic       494
Name: di_language1, dtype: int64

In [33]:
#cell to explore contents of various cells
lang2 = smile_on['di_other_language'].unique()
lang2

array([nan, 'Farsi', 'Amharic', 'Mandarin', 'Burmese', 'Laotian',
       'East African', 'Pakistani', 'Laos', 'Kunama', 'Swahili',
       'English', 'Hindi', 'French', 'Kinyarwanda', 'Vietnam', 'Korean',
       'Vietnamese', 'Bengali', 'Ethiopian', 'Nepali', 'Mayan', 'Persian',
       'Urdu', 'Russian', 'Somali', 'Kurdish', 'Kurdish-Badini',
       'Ahmaric', 'Chinese', 'Armenian', 'Sign Language', 'Romanian',
       'farsi', 'Greek', 'Ukranian', 'hatian', 'Gujrati', 'Ijbo'],
      dtype=object)

In [34]:
smile_on["di_other_language"].value_counts()

Farsi             12
Amharic           10
Mandarin          10
Kurdish           10
Russian            7
Burmese            7
Korean             6
Laotian            5
Vietnamese         5
French             5
Nepali             5
Chinese            4
Somali             4
Laos               4
Hindi              4
Mayan              3
East African       3
Ahmaric            3
Sign Language      3
Kunama             3
Kinyarwanda        2
Swahili            2
Gujrati            2
English            2
hatian             2
Ethiopian          2
Armenian           1
Kurdish-Badini     1
Bengali            1
Romanian           1
Persian            1
Pakistani          1
farsi              1
Ijbo               1
Ukranian           1
Urdu               1
Vietnam            1
Greek              1
Name: di_other_language, dtype: int64

In [35]:
compare_lang = (smile_on['di_language1'].notnull() == smile_on['di_other_language'].notnull()).all()
compare_lang

False

In [36]:
smile_on['di_language'] = smile_on['di_language1'].fillna(smile_on['di_other_language'])
smile_on = smile_on.drop('di_language1', axis=1)
smile_on = smile_on.drop('di_other_language', axis=1)
smile_on.shape

(57486, 113)

# Case Management Info - Combining two columns together

In [37]:
smile_on["cmi_What is the outcome for the client?"].value_counts()

Navigation to dental clinic for dental exam and treatment    570
Name: cmi_What is the outcome for the client?, dtype: int64

In [38]:
compare_call_outcome = (smile_on['cmi_What is the outcome for the client?'].notnull() == smile_on['referrals_made'].notnull()).all()
compare_call_outcome

False

In [39]:
smile_on['referred'] = smile_on['cmi_What is the outcome for the client?'].fillna(smile_on['referrals_made'])
smile_on = smile_on.drop('cmi_What is the outcome for the client?', axis=1)
smile_on = smile_on.drop('referrals_made', axis=1)
smile_on.shape

(57486, 112)

# Client Encounter Next Steps - Combining two columns together

In [40]:
#cell to explore contents of various cells
smile_on['pe_next_step1'].unique()

array(['Continued with Navigation', nan,
       'No further questions from client', 'Refer to Health Match'],
      dtype=object)

In [41]:
#cell to explore contents of various cells
smile_on['pe_next_step2'].unique()

array([nan, 'Continued with Navigation',
       'No further questions from client', 'Refer to Health Match'],
      dtype=object)

In [42]:
compare_pe_next = (smile_on['pe_next_step1'].notnull() == smile_on['pe_next_step2'].notnull()).all()
compare_pe_next

False

In [43]:
smile_on['pe_next_step'] = smile_on['pe_next_step1'].fillna(smile_on['pe_next_step2'])
smile_on = smile_on.drop('pe_next_step1', axis=1)
smile_on = smile_on.drop('pe_next_step2', axis=1)
smile_on.shape

(57486, 111)

# Cleaning column data types

In [44]:
dtypes = smile_on.dtypes

In [45]:
print(dtypes)

2
report_num                 object
reg_or_appt                object
related_reports            object
call_start                 object
call_end                   object
                            ...
ve_eligibility_verified    object
bocq_next_step             object
di_language                object
referred                   object
pe_next_step               object
Length: 111, dtype: object

In [46]:
for col_name in smile_on.columns: 
    print(col_name)

report_num
reg_or_appt
related_reports
call_start
call_end
call_length
patient_id
city
county
state
zip_code
EnteredByWorkerNum
date_entered
di_household_size
birth_year
oec_1351
oec_1354
oec_2140
oec_2150
oec_2160
oec_2161
oec_230
oec_2330
oec_2331
oec_2332
oec_2335
oec_2390
oec_2391
oec_2392
oec_2393
oec_2394
oec_2915
oec_2920
oec_2933
oec_2940
oec_2950
oec_2954
oec_2980
oec_3220
oec_4341
oec_4342
oec_6930
oec_6980
oec_7111
oec_7140
oec_7210
oec_7220
oec_7230
oec_7240
oec_7241
oec_7250
oec_7261
oec_7286
oec_7310
oec_7311
oec_7320
oec_7321
oec_7410
oec_7411
oec_7471
oec_7510
oec_7971
oec_7972
oec_9110
oec_9951
scrn_date_of_last
ve_verified_date
bocq_eat_limited
bocq_dental_clinic
bocq_client_commit
bocq_help_other
bocq_need_help
bocq_appearance
bocq_condition
cmi_clinic
cmi_transport_barriers
cmi_barriers_to_care
ci_Is patient of record date if yes last seen?
ci_Was initial appointment made?
ci_Was initial transportation assistance or referral provided?
di_gender
di_hh_income
di_referred_by
di_race_eth
di_other_programs
di_last_dentist_visit
oec_care_provided
pe_insurance
pe_prequalify
scrn_lower_teeth
scrn_upper_teeth
scrn_has_dentures
scrn_eats_w_dentures
scrn_problems_12m
scrn_tooth_brushing
scrn_periodontal
scrn_root_fragments
scrn_lesions
scrn_urgency
scrn_decay
si_enroller_id
si_enroller_location
tp_completed
tp_developed
tp_yay
ve_transport
ve_eligibility_verified
bocq_next_step
di_language
referred
pe_next_step

In [47]:
#clean typos to convert columns to float
smile_on = smile_on.replace('1_', '1')
smile_on = smile_on.replace('1_____', '1')
smile_on = smile_on.replace('2_', '2')
smile_on = smile_on.replace('2_____', '2')
smile_on = smile_on.replace('3_____', '3')
smile_on = smile_on.replace('4_', '4')
smile_on = smile_on.replace('4_____', '4')
smile_on = smile_on.replace('6_____', '6')
smile_on = smile_on.replace('112___', '11')
smile_on = smile_on.replace('#NUM!', 'NaN')
smile_on = smile_on.replace('#VALUE!', 'NaN')
smile_on = smile_on.replace('______', 'NaN')

In [48]:
smile_on[['oec_1351','oec_1354','oec_2140','oec_2150','oec_2160',
'oec_2161','oec_230','oec_2330','oec_2331','oec_2332','oec_2335',
'oec_2390','oec_2391','oec_2392','oec_2393','oec_2394','oec_2915',
'oec_2920','oec_2933','oec_2940','oec_2950','oec_2954','oec_2980',
'oec_3220','oec_4341','oec_4342','oec_6930','oec_6980','oec_7111',
'oec_7140','oec_7210','oec_7220','oec_7230','oec_7240','oec_7241',
'oec_7250','oec_7261','oec_7286','oec_7310','oec_7311','oec_7320',
'oec_7321','oec_7410','oec_7411','oec_7471','oec_7510','oec_7971',
'oec_7972','oec_9110','oec_9951','birth_year','di_household_size']].apply(lambda x: x.astype('float'))

2,oec_1351,oec_1354,oec_2140,oec_2150,oec_2160,oec_2161,oec_230,oec_2330,oec_2331,oec_2332,...,oec_7410,oec_7411,oec_7471,oec_7510,oec_7971,oec_7972,oec_9110,oec_9951,birth_year,di_household_size
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1960.0,1.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1959.0,1.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1942.0,1.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1960.0,1.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1955.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1957.0,2.0
57856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1958.0,1.0
57857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1900.0,NaN
57858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1958.0,1.0
57859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1958.0,1.0

In [49]:
#cell to explore contents of various cells
smile_on['scrn_has_dentures'].unique()

array([nan, 'No', 'Upper', 'Upper; Lower', 'Lower', 'No; Upper',
       'No; Upper; Lower'], dtype=object)

In [50]:
column_dtype = smile_on.iloc[:, [3,75]]
column_dtype

2           call_start                          cmi_transport_barriers
0      9/30/2021 16:56                                             NaN
1      9/30/2021 16:53                                             NaN
2      9/30/2021 16:50                                             NaN
3      9/30/2021 16:48                                             NaN
4      9/30/2021 16:46  Availability - no car/access to transportation
...                ...                                             ...
57855    8/1/2018 8:00                                             NaN
57856   5/31/2018 8:27                                             NaN
57857  5/23/2018 14:11                                             NaN
57858   5/15/2018 9:06                                             NaN
57859   5/10/2018 8:25                                             NaN

[57486 rows x 2 columns]

In [51]:
smile_on.dtypes['call_end']

dtype('O')

In [52]:
smile_on.dtypes['call_start']

dtype('O')

In [53]:
smile_on['call_start'] = smile_on['call_start'].astype('datetime64[ns]')
smile_on['call_end'] = smile_on['call_end'].astype('datetime64[ns]')

In [54]:
smile_on.dtypes['call_start']

dtype('<M8[ns]')

In [55]:
smile_on.dtypes['cmi_transport_barriers']

dtype('O')

In [56]:
smile_on.to_csv('../data/smile_on_clean.csv')

In [57]:
#combining two columns that have the same information, but only one seems to be used depending on the record
#smile_on = smile_on['bocq_next_step1'].fillna(smile_on['bocq_next_step2'])

In [58]:
# how many clinics drafted treatment plans? (not necessarily indicator of success if treatment plan was not needed)
# how many clinics restored full functionality to patient?
# how many clinics saw a patient multiple times?
# for how many people was transportation arranged if they needed it?